### ISSUE TITLE
Building - Electrical Permit - Inground Pool

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#101]
System generated additional inspections for Electrical permit for in ground pool. Applicable inspections should only include:
- Bonding
- Trench (Underground)
- Pool/Deck
- FInal

AP 237163
Logged by M. Coffman

![inground](https://user-images.githubusercontent.com/4129185/53142608-8d961080-3562-11e9-98a8-805540ebc5d8.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Update formulas so that ELEC-TEMP and ELEC-RI don't get added anymore in this scenario for INPOOL
ElecPerm_RI_Insp_AOC
ElectPerm_INspTemp_Aoc
ElectPerm_InspBondDeck_AOC

Please screenshot for proof of test (AP#236166 in DEV)
<img width="960" alt="issue101_fixed" src="https://user-images.githubusercontent.com/47784290/53212606-8ed34600-3613-11e9-82f3-6203a5b09e01.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fix

**Comment by dhenry-KCI** [comment]
Confirmed Fix
