### ISSUE TITLE
Building - Basement Finish - Fire Permit Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#104]
In addition to the Automation and Application fees that correctly generated, the system should have also generated:
- Plan Review for FS 13D - $115.00
- Inspection Fee for FS13D - $152.00

If there are 10 sprinkler heads or less (13 D sprinkler system) - flat rate of $178 fee applies (no plan review or Inspection Fee)

![fire fees](https://user-images.githubusercontent.com/4129185/53251639-1c9e4800-368b-11e9-98cf-1a42244193a3.png)

**Comment by megisys** [comment]
How many Levels does the building have ? We check to see under 4.. This permit has 0 stories . Can add check it is always great than 1 ? @ABonomo21 

![image](https://user-images.githubusercontent.com/47392306/53685664-ac776e00-3ceb-11e9-8a2a-4482b826ca92.png)

**Comment by imazlout** [comment]
This fire permit has an occupancy code of RESTOW, which is why the fees weren't added because there were no levels on the building details of the attached application. These were the requirements that came out of the testing sessions after the CRP. Please let me know if they have changed, and if so, what are the new requirements?

**_"If attached RESTOW has 4 or more levels (on Building Details), then 'PLAN REVIEW FOR FS 13 &13R' and 'INSPECTION FEE FOR FS 13 & 13R' are added instead of the 'PLAN REVIEW FEE FOR FS 13D' and 'INSPECTION FEE FOR FS 13D' fees"_**

**Comment by ABonomo21** [comment]
The number of stories does not affect this **suppression type**, the number of stories is only applicable to a **permit type** of "alarm".

**Comment by ABonomo21** [comment]
fees generated correctly-aw
![image](https://user-images.githubusercontent.com/47611580/55639473-7cfacc00-5797-11e9-8c86-bf96fb177fd3.png)
