### ISSUE TITLE
License - Special Event - Milestone Progression after Under Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1072]
After approving all of the Under Review reviews, the application progresses straight to the Active milestone. It bypasses the Awaiting Fee Payment and Issue License milestones. A $10.00 Special Event Permit fee generates but is not required to be paid. There are also no additional status checks on the application.

![image](https://user-images.githubusercontent.com/31770504/59050193-be6f2c80-8857-11e9-9e81-079e6e494b8a.png)

![image](https://user-images.githubusercontent.com/31770504/59050214-c929c180-8857-11e9-805f-491003c9de49.png)

![image](https://user-images.githubusercontent.com/31770504/59050234-d941a100-8857-11e9-97b2-e938cf50eb29.png)

![image](https://user-images.githubusercontent.com/31770504/59050345-232a8700-8858-11e9-85c3-9c5b70586e75.png)

**Comment by calequin** [comment]
The issue here is that the fee quanitity originates from the number of days in the special event detail page. There is two detail pages now. One is for intake and the other is for backoffice. The backoffice needs to be filled out with the number of days in order for the quantity to be correct. Once the quantity is listed then the fee status check will stop the application. Please retest or contact me for more info

**Comment by JuanitaMiles** [comment]
Looks good for now.
