### ISSUE TITLE
License - Plumbing License - Status Dates Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#11]
We need to confirm/update the configuration on the all of the dates within the Status Dates section on the License Description tab. The rules for each date are as follows:

- [x] License Date: This date should be the date processed. Change the name of this field to 
      "Process Date".
- [x] Issued Date: This date should be the original license issuance date.
- [x] Last Renewal: This date should populate based on the renewal date.
- [x] Next Renewal: This date should the eligible date for accepting new or renewed license 
      applications. (90 days prior to expiry date of the current license term)
        *A notification should be sent to current license holders (active licenses).
- [x] Expires: This date should always be 11/13 of the odd year for plumbing licenses.
- [x] Grace Exp: This date should be 90 days after the expiry date (11/13). After this date, the 
      application should no longer allow for renewals to be accepted.

![image](https://user-images.githubusercontent.com/31770504/52386783-711fb180-2a55-11e9-8481-4af685b6b7f7.png)

**Comment by calequin** [comment]
Before renewal screenshot
![renewal 1](https://user-images.githubusercontent.com/47603568/53364606-c9cfc500-3904-11e9-8067-9d0d6763afd7.PNG)

After renewal screenshot
![renewal 2](https://user-images.githubusercontent.com/47603568/53364659-ee2ba180-3904-11e9-8c35-f07c4d788f07.PNG)

**Comment by ABonomo21** [comment]
When looking up an old expire plumbing license, when you first open it shows that the License is Active and the Current Milestone is Pre-Renew. Once the check status button is clicked, the License stays in Active, the Current Milestone changes to Awaiting Renewal Details, a renewal fee is automatically added, and the process date changes to today even though nothing has been processed (only the check status button was clicked). The License is expired through out all of this so it should not show as active.  Not sure if this is due to a data migration issue or not.-AW

License:
![image](https://user-images.githubusercontent.com/47611580/54756287-4da46680-4bbe-11e9-885b-71fd81dafe64.png)

After clicking the check status button:
![image](https://user-images.githubusercontent.com/47611580/54756333-67de4480-4bbe-11e9-8ccb-6560f9f7e425.png)

**Comment by goggansd** [comment]
@megisys has informed me that while this is a data issue, it will require running the post data migration tool again in a fresh environment. Setting to Will Monitor.

**Comment by calequin** [comment]
fixed
