### ISSUE TITLE
R4C- Special Event - Intake Language

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1140]
Please update the R4C intake details language
- Rename the event "Special Events 1 Day Liquor License - Request"
Under Instructions
- This is an event request form. Upon approval you will receive an application for a per diem license to complete and submit
- Please submit your request at least two weeks prior to the event start date

**Comment by JuanitaMiles** [comment]
The County changed the language above since submitting this issue. I have updated the portal language as follows: 

**Special Event Request Submission Requirements:**
- This is an event request form. Please submit your request at least **two weeks prior to the event start date**. Failure to submit your request within this time frame may result in the assessment of a late fee.

**At the time of submitting your request, please upload the following as Attachments to your online request:**
- A completed event application. The special event application can be found on the Frederick County Liquor Board website using the following link: **[insert link to online application]**
- A diagram of the event space.
- Applicants may optionally upload any additional documents pertaining to their event request. (Alcohol Plan, Alcohol Awareness Certificates, 501c3, etc)

**Comment by JuanitaMiles** [comment]
Fixed

**Comment by JuanitaMiles** [comment]
updated further based on Ashley's request.
