### ISSUE TITLE
ips-preprod-planning-in life mapping-plat-pre-finalized should go to admin closure and another fee popping up

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1209]
Hansen=pre-finalize.  Should go to admin closure in IPS but it is in prte-approve application.
Also, a $58 fee is due in IPS but not in Hansen
MW

![image](https://user-images.githubusercontent.com/4129185/59711563-54507300-91d9-11e9-84d2-2d79e3bfee7d.png)

**Comment by goggansd** [comment]
@megisys, the plan for these was to have them migrate into the same milestone as already existed in V7, then have a batch process run after migration to move the applications to the appropriate next milestone. Did this happen after the last migration run? If not, then this is likely the cause. But talking to @calequin he indicates that there were some formulas written by @megisys for Trade or Business License to address this because there were some unexpected issues due to the County using the status as the indication of the stage progression in V7 instead of using the stage name itself. Does this ring a bell? Or do we have to map these? Or are there formulas which need to be written for this Product Family as well?

**Comment by dhenry-KCI** [comment]
6/24/19: its now in awaiting payment.  Where did this payment come from?  As noted above, Hansen does not have any fees due.  MW

![image](https://user-images.githubusercontent.com/4129185/60037700-46d73500-9680-11e9-9cc2-9c8cc602f89b.png)
