### ISSUE TITLE
ips-preprod-planning-in life mapping-plat-pre-finalized should go to admin closure but it closed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1210]
![image](https://user-images.githubusercontent.com/4129185/59711897-0ab45800-91da-11e9-96ae-21ad3a59feed.png)

MW

**Comment by goggansd** [comment]
@megisys, the plan for these was to have them migrate into the same milestone as already existed in V7, then have a batch process run after migration to move the applications to the appropriate next milestone. Did this happen after the last migration run? If not, then this is likely the cause. But talking to @calequin he indicates that there were some formulas written by @megisys for Trade or Business License to address this because there were some unexpected issues due to the County using the status as the indication of the stage progression in V7 instead of using the stage name itself. Does this ring a bell? Or do we have to map these? Or are there formulas which need to be written for this Product Family as well?

**Comment by megisys** [comment]
I have a utility written
Rules are in the application on WH-IPSDEVTST

**Comment by dhenry-KCI** [comment]
not fixed 6/24/19-MW
