### ISSUE TITLE
Grading- SWM Report Modifications & IPS change to details tab

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1211]
PLease see attached for the changes to be made in IPS under the inspection details for SWM permits. This also includes the report itself and changes to be made - however, we have made Tara aware of this already.

[SWM Report Mark Up.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3306923/SWM.Report.Mark.Up.pdf)

![image](https://user-images.githubusercontent.com/47611580/59781632-34c55300-928a-11e9-9a33-c5fde07fc1df.png)

![image](https://user-images.githubusercontent.com/47611580/59781660-40187e80-928a-11e9-9b1e-8fe19d25c3a2.png)

Eric Dodson/Tiffany Martin 6/19/19

**Comment by megisys** [comment]
Tara move where needed

**Comment by dhenry-KCI** [comment]
@megisys - based on the language in the error record, there are two issues - one a change to be made in IPS (infor) and an update for reporting (Tara). Please confirm that your issue has been addressed.

**Comment by megisys** [comment]
What Error Record ?

**Comment by TaraF** [comment]
This is ready to re-test - report updated based on the notes above.  Please note, like the other inspection reports, this deployment still requires plugging in the INSPECTNO, since INFOR is still looking into / fixing that issue.

Also, noting here, there is currently not many examples to test, please use INSPECTNO 976696 (within APNO 171885).

![image](https://user-images.githubusercontent.com/4104464/66223710-1f8dfc00-e6a2-11e9-83c4-053427f02181.png)

**Comment by megisys** [comment]
Case Sensitive.. Ensure the parameters are perfect @TaraF

**Comment by ABonomo21** [comment]
not sure what this ticket is for. may need to meet with tara and eric to confirm. @dhenry-KCI
