### ISSUE TITLE
Addendum-Issues/reminders to check

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1237]
Reminder for Ashlye, Dan, and I-AW
-Need to decide if $10 auto enhancement fee should be charged.
-Should addendum permit numbers be new numbers or same number as parent permit with A,B,C        
        or -1,2 3,  etc. 
-Should the $26 revision fee auto generate? (it currently does not)

**Comment by megisys** [comment]
Same as Parent After associating with a R1 and so on
$26 fee should auto add on fees milestone

**Comment by imazlout** [comment]
Ready for test in test

moved $26 fee so that it gets added on completeness check (there is no Add Fees milestone since fees get added manually)

Once parent is attached, Addendum gets renamed to the parent permit number with a sequence number attached at the end: for example, if parent app number is “246870”, the addendum will say “246870-1” and then if they do another addendum it will say “246870-2” and so on...

**Comment by ABonomo21** [comment]
fixed- $26 fee are automatically generated and the permit numbers are changing to the correct number sequence-AW
