### ISSUE TITLE
Reports _ Supported browser for SSRS

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1411]
unable to launch a report in IPS 11 Test for Chrome
![image](https://user-images.githubusercontent.com/47611580/62484871-1dceb780-b789-11e9-9f4e-bac81737727d.png)
tried to run an on demand report for application G244610

**Comment by ABonomo21** [comment]
we need to get a solution for the multiple browser issues !

**Comment by megisys** [comment]
Dave. Addressed this issue

**Comment by JuanitaMiles** [comment]
The Gaming Official Issuance on demand report still will not launch in Chrome. Report name is _Gaming Permit - Official Issuance (Bingo, Raffle, TipJar On Prem, TipJar Off Prem, Fire Dept.)_

![image](https://user-images.githubusercontent.com/31770504/63276732-f6d8b100-c271-11e9-96a6-16490cf7a512.png)

**Comment by megisys** [comment]
Hi Guys, the hold letter works. as i mentioned to Tara.. There is something in this report as others are working. It is an SSRS issue with Chrome for this report and I can not assist as I am not an expert in either of those technologies

**Comment by ABonomo21** [comment]
related to ticket #1439 

i am not able to view reports in chrome but can in IE. this needs to be fixed

**Comment by TaraF** [comment]
Noting: All reports have been migrated to SQL Server 2016 Reporting Services as provided by IIT.  They are launching fine from Chrome in SSRS, so it seems to be tied to IPS deployment on the Infor side.  With that said, KCI will try to look into figuring out why the issue seems only isolated to some reports, but not all, to help troubleshoot the issue.

**Comment by ABonomo21** [comment]
will email tara if unable to open any reports when they come up.
