### ISSUE TITLE
Reports- Time 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1439]
Any time  in IPS is generated as military time- reports should be converted to 12 hr clock

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/62548984-b15dc200-b835-11e9-9266-49a4c0cc27fc.png)

**Comment by megisys** [comment]
Please Convert on the Report Side

**Comment by JuanitaMiles** [comment]
The Hours of Operation section is now missing completely. I believe there was a change to this grid due to another configuration issue ( #1421 ) so this might be the reason for it not showing on the report.

![image](https://user-images.githubusercontent.com/31770504/65442730-bb924a80-ddfa-11e9-9c93-7948a7babaa7.png)

![image](https://user-images.githubusercontent.com/31770504/65442769-cea51a80-ddfa-11e9-9075-faffcb43f9c4.png)

**Comment by TaraF** [comment]
Ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65972416-ccb10c00-e437-11e9-87a4-c277989703e4.png)
report is not available

**Comment by TaraF** [comment]
![image](https://user-images.githubusercontent.com/4104464/65972972-9922b180-e438-11e9-8b5b-3e28954d225f.png)

**Comment by ABonomo21** [comment]
Thanks
