### ISSUE TITLE
Resbldg- notification

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1559]
never got an email notification that building permit 246191 was issued
should have generated an issued permit and placard

**Comment by mmbanong** [comment]
I am able to generate the fee payment notification and permit issuance notification. Ran the correspondence batch job a couple of times, checked history but it did not run

**Comment by dhenry-KCI** [comment]
@mmbanong sounds like this is still an issue. Let's discuss tomorrow.

**Comment by mmbanong** [comment]
I created a RESBLDG application and got the notifications but not the correspondence. The correspondence has been returning this error since 8/27/2019. I was able to download the permit but not emailed as expected. Dan can you take a look at the correspondence error message



![correspondence error](https://user-images.githubusercontent.com/47392173/63939361-1cfe0e00-ca35-11e9-8ddd-6c92168967e6.PNG)


[Building_Permit_-_Official_Issuance_MMBANONG_20190829_080203383.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3555471/Building_Permit_-_Official_Issuance_MMBANONG_20190829_080203383.pdf)

**Comment by dhenry-KCI** [comment]
@mmbanong - The issue with corresondence management not firing has been resolved by the Infor product team. Please go into the correspondence schedule (batch manager job) and fix any Cm reports that are still erroring as some can't find the correct report.

**Comment by mmbanong** [comment]
Notification and correspondence both generated
[FRO Notification.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3596985/FRO.Notification.pdf)
[FRO_Permit_-_Official_Placard_JWISNER_20190910_012533154.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3596987/FRO_Permit_-_Official_Placard_JWISNER_20190910_012533154.pdf)

Fredrick has been updated to Frederick for all scheduled correspondences
![image](https://user-images.githubusercontent.com/47392173/64636157-20977a80-d3cf-11e9-8550-39c821d1955b.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
