### ISSUE TITLE
Resbldg- Apartment Parent

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1666]
Apartment parent is status checking for the associated permits to be issued- this is not required
![image](https://user-images.githubusercontent.com/47611580/63886939-99e3a600-c9a9-11e9-8fc2-6fbb54f89ce9.png)

**Comment by JuanitaMiles** [comment]
I'm stuck in a loop here...the Parent (246500) is stuck in the Under Review milestone because it wants the child permits to be issued before it can progress, but the Units all have a status check that is asking for the Parent to be issued.
![image](https://user-images.githubusercontent.com/31770504/64292376-44267500-cf38-11e9-8adc-dcc7f2d57683.png)

![image](https://user-images.githubusercontent.com/31770504/64292455-72a45000-cf38-11e9-90dd-059d06aca6b5.png)

**Comment by ABonomo21** [comment]
246581(parent ) and 245832 worked child waited for parent to issue but the parent did not wait for the child. 
9.5.19 ab fixed
