### ISSUE TITLE
PLANNING - R4C - screen not resizing with all options

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1670]
Options missing when screen not full size
AR
![image](https://user-images.githubusercontent.com/4129185/63947046-39ee0d80-ca44-11e9-91d0-05c09a3e8945.png)

![image](https://user-images.githubusercontent.com/4129185/63947094-4e320a80-ca44-11e9-861a-697368dc0df1.png)

**Comment by calequin** [comment]
The responsive design (when the screen is resized) of the website places the links in the left hand side under the three dashes (Hamburger Icon). This is so that mobile users can navigate without accidentally clicking on a link.

![image](https://user-images.githubusercontent.com/47603568/63947529-b0870d00-ca3c-11e9-82b3-a9ab82abfefb.png)

**Comment by dhenry-KCI** [comment]
Ok. areed
