### ISSUE TITLE
Fire Alarm Permit- License required 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1747]
License required on alarm permit is showing as for a sprinkler license.... this is not correct 
![image](https://user-images.githubusercontent.com/47611580/64203232-fc80ea00-ce60-11e9-9b31-f945cccb6404.png)

**Comment by calequin** [comment]
the reason this isnt working properly is because this requirement is set prior to completeness check. but the backoffice does not update the detail page until completeness check therefore the required license field is not populating correctly.
A workaround would be to place the required licenses as a status check on completeness check

**Comment by ABonomo21** [comment]
fixed confirmed 9.4.19
![image](https://user-images.githubusercontent.com/47611580/64264452-50daa700-ceff-11e9-86ca-1af7bcd19379.png)
