### ISSUE TITLE
USe-Home Occupation Official Issuance 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1969]
See highlighted areas on report to see where changes need to be made 
Business name should pull from the A/P Name 
Type of business should pull from the work type 
home occupation will be located in should pull from the details page 
square footage should generate on one line not two 
private or common drive should pull from the details page 
date formatting should be consistent 
day... thru day should be corrected 
total paid - $0.00????

![image](https://user-images.githubusercontent.com/47611580/66154555-bcda2900-e5eb-11e9-8d53-17e16d82b455.png)

![image](https://user-images.githubusercontent.com/47611580/66154578-c9f71800-e5eb-11e9-9df9-a7f202cd51b7.png)
![image](https://user-images.githubusercontent.com/47611580/66154613-e1ce9c00-e5eb-11e9-91c6-9ecd4137966d.png)

finally, i would like the formatting to be consistent as far as capital letters or lower case letters- i know this is being pulled by how it is in the system but i think it would look better if it was all uniform. 
![image](https://user-images.githubusercontent.com/47611580/66154750-2ce8af00-e5ec-11e9-9373-ab061c075f01.png)

please let me know if you have questions

**Comment by TaraF** [comment]
This fixes have been made.  Noting here the following:

- Business Name / Type of Business were being handled correctly so far as the old report example we were given to use.  They have now be changed to reflect request made above.

- Days/Hours of Operation - it is not clear in the comments above what is being called out as wrong.  The text matches what is in the old as 'Thru'.  We were requested to update the IPS military time to show 12 hour time, so if the issue is with 00:00 military time for End Hour, that is being handled as requested (12:00 AM).  

All other issues are fixed and ready for re-test.

**Comment by ABonomo21** [comment]
two minor changes and tara will correct
