### ISSUE TITLE
Use- Land Use Placard 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1981]
Tara can you send me the final qc notes on the land use placard- i have some question about Type: and what we wanted at the bottom for event date and permit expiration date 

![image](https://user-images.githubusercontent.com/47611580/66157804-8c49bd80-e5f2-11e9-8755-df1f678372ec.png)

**Comment by TaraF** [comment]
@ABonomo21  sure - here is the latest document you sent us (5/9/2019), which talk about event and permit date:
[ReportsChanges_SingleUsePlacard.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3691168/ReportsChanges_SingleUsePlacard.docx)

As far as the other fields, here is what we received in April:
[placardupdates_LandUse.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3691170/placardupdates_LandUse.docx)

And then in August, I noted based on Gary's feedback on all placards:
"Per a meeting with the director, they would also like to drop the seal in the upper left corner (since the watermark seal is already there). Please then center the top text appropriately."
