### ISSUE TITLE
Building-Non Res Demo Issues.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#226]
The Zoning Fee and Zoning Dept Review did not generate. 
![image](https://user-images.githubusercontent.com/47611580/53982084-fbeddd80-40e1-11e9-8965-3acde88ebc18.png)
![image](https://user-images.githubusercontent.com/47611580/53982093-04461880-40e2-11e9-815f-ac50c725dfba.png)

**Comment by megisys** [comment]
Should it ALWAYS @ABonomo21  ??

**Comment by ABonomo21** [comment]
The Zoning Fee/Zoning Review should generate for all properties not within an incorporated town.-AW

**Comment by ABonomo21** [comment]
This Non Res Demo Permit had the Zoning Fee and the Building Fee generate but the Zoning and the Building reviews did not generate-AW
![image](https://user-images.githubusercontent.com/47611580/53984998-8df8e480-40e8-11e9-95f3-e36f0f4ade84.png)
![image](https://user-images.githubusercontent.com/47611580/53985015-96e9b600-40e8-11e9-81d7-740624a231b0.png)

**Comment by ABonomo21** [comment]
For Non Res Demo permits, the additional electric and plumbing checkboxes are correct however the red line on the check status should not generate. This will something that the inspectors will verify out in the field per ABonomo-AW
![image](https://user-images.githubusercontent.com/47611580/53985238-1e372980-40e9-11e9-9a2c-a4763226f5ef.png)

**Comment by ABonomo21** [comment]
This non res demo permit is on public water/sewer but the demolition type is burn so health fee/review needs to generate. the zoning fee also did not generate.
![image](https://user-images.githubusercontent.com/47611580/53985887-c6012700-40ea-11e9-9553-9d55a3b87c83.png)

![image](https://user-images.githubusercontent.com/47611580/53985941-e4672280-40ea-11e9-8c91-33736c5f51bd.png)

**Comment by imazlout** [comment]
Following is ready to test.

- Zoning Fee - Add if incorporated = False
- Zoning Review - Add if incorporated = False (wasn't adding due to migration issue)
- Health Fee - Add if water = well or sewer = septic or Demolition Method = Burn
- Health Review - Add if water = well or sewer = septic or Demolition Method = Burn
- Status checks (red line) for electrical and plumbing permit attachment have been expired.

### **Question:** @ABonomo21 
**Building Review - which one is this? the only review that has the word Building in it is PLNREV, which did populate (it's set to always add).**

@dhenry-KCI could we make sure that we don't have multiple issues in the same ticket put in as comments. It made it time consuming for me to sort through to make sure I didn't miss anything.

**Comment by ABonomo21** [comment]
Confirmed Fixed-Reviews and Fees generated correctly. My error before with the building review, it did generate on the previous permit-AW

![image](https://user-images.githubusercontent.com/47611580/54131947-bd119d80-43e9-11e9-9548-1c4b4da4aedb.png)
