### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2264]
Received two coorespondence - COC and COO 
New SFD permit #251106
both of them attached in R4C for applicant to download
both of them were sent out via emails (2 separate)
ONLY Certificate of Occupancy should be sent 

![image](https://user-images.githubusercontent.com/47611580/68783798-8c81a380-0609-11ea-823d-5352dec89d67.png)

11/13/13 EP

**Comment by TaraF** [comment]
This has been reset in IPS, and is working there.  Ready for re-test.

**Comment by ABonomo21** [comment]
still received both the certificate of completion and the certificate of occupancy- should have only gotten the certificate of occupancy 
![image](https://user-images.githubusercontent.com/47611580/68873733-109d5f00-06ce-11ea-8727-f1aa1c73641c.png)

**Comment by TaraF** [comment]
I am not seeing what is noted above.  I created and ran a new RESBLDG (since that is the sample above), and this is my result (only one COO):

![image](https://user-images.githubusercontent.com/4104464/69396583-ba718280-0cb0-11ea-9f3d-d63135068de5.png)

If you are still running into this, I need to sit down with someone as they do it and see it happening since I cannot replicate.

**Comment by ABonomo21** [comment]
corrected # 251528
