### ISSUE TITLE
Plumbing Demo-Minimum Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#229]
Residential Plumbing Demo Permit- If the Work Type is "Remove" then the permit should generate minimum fees-MCoffman

Permit#238645

![image](https://user-images.githubusercontent.com/47611580/53985050-b2ed5780-40e8-11e9-9ae3-93ba2dc1efe7.png)

![image](https://user-images.githubusercontent.com/47611580/53985081-c5679100-40e8-11e9-8403-70ff1239b20a.png)

**Comment by imazlout** [comment]
According to Hansen 7 minimum fees only get added for REAPFL. If work type = Remove, then the demo fee gets added (for res and nonres respectively), which was part of fix for #96 which has since been closed. Are you sure this request is correct? Please see export from Hansen 7 prod below:

<img width="960" alt="issue229" src="https://user-images.githubusercontent.com/47784290/53990911-60676780-40f7-11e9-82a0-b3bcb3e49b33.png">

**Comment by ABonomo21** [comment]
@imazlout 
This is correct. I was saying that on Residential Plumbing Permits when the work type is Remove the Demo fee (which is the residential plumbing minimum fee of $48.00) should generate. 

On Non-Residential Plumbing Permits when the work type is Remove, the Demo fee of $115.00 should generate (which is the minimum fee for non-residential plumbing permits)-MCoffman

Permit# 238815- Both the Residential Minimum fee, and the Demo Fee generated-Not Correct
![image](https://user-images.githubusercontent.com/47611580/54366710-820ca580-4647-11e9-8a48-34355476cc5b.png)

**Comment by imazlout** [comment]
Ready for test.
Only the automation fee and res demo fee get added now.

**Comment by ABonomo21** [comment]
Corrected-MCoffman

Permit# 238870-Residential Plumbing Demo-Fixed
![image](https://user-images.githubusercontent.com/47611580/54439969-3540d180-4710-11e9-8058-987508ab0412.png)

Permit# 238872- Non-Residential Demo-Fixed
![image](https://user-images.githubusercontent.com/47611580/54440835-d714ee00-4711-11e9-9a47-181f9fbae403.png)
