### ISSUE TITLE
Holds- Notification/Report Correspondence 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2349]
Need to work with Tara and Dan on the hold reports and how the notifications will be sent out for P&I, U&O and OLS holds

**Comment by megisys** [comment]
Add a Log. Which will send Notification and then a Condition

**Comment by dhenry-KCI** [comment]
@ABonomo21 @megisys trying to understand the movement on this ticket. Is this ready for retest based on Dan's comment?

**Comment by megisys** [comment]
I need to know the COrrepondance setup here and the report

**Comment by TaraF** [comment]
@megisys  - the report is ready, passing it back over to you.

Please note, I didn't set up any AOC, since there is no milestone trigger for this.  I did set up SLCP, and the report under the General folder of SRM. 

SSRS report name: BuildingUIHolds 

SLCP name: Building Permit - Hold Letter

General, SRM name:  Building Permit - Hold Letter

![image](https://user-images.githubusercontent.com/4104464/70068084-5b1f4680-15bd-11ea-8e40-28455574b2f4.png)

**Comment by dhenry-KCI** [comment]
closed go-live weekend.
