### ISSUE TITLE
Demo Residential Building-Pending Certificate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#236]
After Final Inspection is completed the milestone should change to "Pending Certificate" and instead it is showing as "Admin Closure"; needs to be changed to say "Pending Certificate"-MCoffman

![image](https://user-images.githubusercontent.com/47611580/53987184-4a08de00-40ee-11e9-9be5-84cd3acf71cd.png)

**Comment by imazlout** [comment]
Although I didn't make this change, it looks to like it was done recently, since Admin Closure milestone doesn't exist for Demo in other environments. DEMO permit type never had a pending certificate milestone even in the old environments. It use to go from Final Inspection straight to Complete, but now there is an Admin Closure milestone added in between. Since I don't know the history of why this change is made, I do not want to make any changes to it. @dhenry-KCI @ABonomo21 @megisys Do either of you guys have input on the request to add Admin Closure milestone?

**Comment by megisys** [comment]
@imazlout @ABonomo21  I was asked for a review to be added after final inspection resulted. So only way was to add a Admin Close step..  Seems like someone is making design changes :)
@dhenry-KCI

**Comment by imazlout** [comment]
Updated to have pending certificate milestone and issue certificate milestone

**Comment by ABonomo21** [comment]
Permit# 238867 RES-DEMO- unable to test because when I try to result the Final Building Inspection as passed, I get this error -MCoffman

![image](https://user-images.githubusercontent.com/47611580/54438196-936bb580-470c-11e9-83cf-20b9408003aa.png)

**Comment by imazlout** [comment]
Ready for test. Now permit moves to the next milestone. Please test with a new application since I resulted the inspection in your test permit to make sure it works.

**Comment by ABonomo21** [comment]
Corrected-MCoffman

Permit# 238914- Residential Building Demo Entire Structure-Corrected
![image](https://user-images.githubusercontent.com/47611580/54556145-9e357d00-498e-11e9-8afb-29a24799d9c2.png)

Permit# 238915-Residential Building Demo Partial Structure-Corrected
![image](https://user-images.githubusercontent.com/47611580/54556434-3cc1de00-498f-11e9-85e5-e8ea0fbdb232.png)

Permit# 238916- Non-Residential Building Demo Entire Structure-Corrected
![image](https://user-images.githubusercontent.com/47611580/54556808-13ee1880-4990-11e9-9ea8-0ab20b8d9206.png)

Permit# 238917-Non-Residential Building Demo Partial Structure-Corrected
![image](https://user-images.githubusercontent.com/47611580/54556945-6fb8a180-4990-11e9-9e4e-fcd6cbe0f836.png)
