### ISSUE TITLE
Building - RESUSES - Cannot create a new application 

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#237]
A new Building - RESUSES application cannot be created.  All required fields are filled out, with the exception of the last Section Complete on the Details tab.  The system will not allow typing ('Y') in the box, nor does the dropdown allow any selections, nor is there a search/selection icon to click.   The field is required however, so the application cannot be saved/created and cannot move forward. 

AP:  any new
Logged By: Tara F

![image](https://user-images.githubusercontent.com/4104464/53988243-0794d080-40f1-11e9-8907-5d561750fb5a.png)

**Comment by imazlout** [comment]
From what I understand, the detail pages are in the middle of a redesign so that they can be made compatible with Rhythm for Civics. It seems that as a result of that effort, the section complete field that  used to be an edit box with a code def pop-up,  is now a drop-down with no options configured for it yet. Assigning to Dan (@megisys ) so that he can update you on when this effort is completed.

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
Confirmed fixed-AW-Permit created and closed.
![image](https://user-images.githubusercontent.com/47611580/54128462-82583700-43e2-11e9-839f-638445fd795a.png)
