### ISSUE TITLE
PLANNING-APFO  LOU FEE MINOR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#279]
APFO minor LOU fee should add after first review cycle when DRTE selects resubmit. Went to awaiting applicant revisions without $405 being added . AREED
![image](https://user-images.githubusercontent.com/4129185/54209224-c5360f80-44b3-11e9-9a59-387bdc3ba86f.png)
![image](https://user-images.githubusercontent.com/4129185/54209364-08907e00-44b4-11e9-9da1-8d04a6113eb7.png)

**Comment by megisys** [comment]
What about the other options.. Do they have a similar impact..

**Comment by dhenry-KCI** [comment]
Same happened on Major LOU fee is $2,103, Modified LOU A239073 fee is $405

![image](https://user-images.githubusercontent.com/4129185/55432697-93b7dd80-5561-11e9-99e4-530ee661e589.png)
![image](https://user-images.githubusercontent.com/4129185/55432707-9b778200-5561-11e9-81c6-2db796e76d36.png)


![image](https://user-images.githubusercontent.com/4129185/55432630-5eab8b00-5561-11e9-8a0e-c11e8662e2b6.png)
![image](https://user-images.githubusercontent.com/4129185/55432642-679c5c80-5561-11e9-8316-ed9e203aab8a.png)

**Comment by goggansd** [comment]
MAJOR LOU FEE was expired back in 2011. Corrected LOU MINOR FEE and MODIFIED LOU FEE to add in Add Revision Fees milestone. Fee amounts were already correct for these two fees. Found a fee called EXECUTION FEE - LOU ALL and made assumption this is the new name for MAJOR LOU FEE since it was active already and had LOU in the fee description and the amount matched the MAJOR LOU FEE amount described above, and made same correction. Please retest.

**Comment by dhenry-KCI** [comment]
major LOU fee= execution fee-LOU ALL and is now correct.

minor LOU fee is now correct

modified LOU is correct


MW
