### ISSUE TITLE
Building - All AP Types - Overpayment/Recalculate Option 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#292]
Attached a planning permit that had a higher valuation amount and calculated the fees based on that. However, I choose the wrong one and I corrected it to be the correct planning permit and the old fees were still there. The overpayment/recalculate fees buttons were not working. 

AP # 238771

logged by Tiffany Martin 3/12/19

**Comment by megisys** [comment]
I need steps to replicate.. Please schedule a time with Dan to replicate

**Comment by dhenry-KCI** [comment]
1. User clicks recalculate fee link
2 select fee to be recalculated
3. click calculator

Calculator never opens and IPS returns to Fees tab.

**Comment by goggansd** [comment]
This is not an issue. This is how the product is designed to work (the calculator is only an icon for the button--the button never launches any kind of calculator application). Instead, the product simply recalculates selected fees based on the same workflow/business rules. It assumes that the user knows that something has changed which would cause the fee value to be different if recalculated. For example, if the fee amount changes on July 1, and the fee needs to be recalculated based on the new fee structure (which has been updated by an Administrator elsewhere in the system's setup), the Recalculate button would cause the fee to be charged at the new rate instead of the old rate. Likewise, if a workflow formula calculates the fee, and the workflow formula changes between the time the fee was initially added and the time the user clicks the Recalculate button, the workflow formula will run again (this time with different code), effectively making the fee value change due to the newly implemented workflow.

**Comment by ABonomo21** [comment]
closed - training issue
