### ISSUE TITLE
Non Res - Tenant/Change of Use - Missing Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#306]
The system is missing inspections for a Non Res , tenant change of use. The system only generated the Building Insulation Inspection. The system is missing the Framing, Ceiling Inspections and Fire Final. (See airtable  https://airtable.com/tblgyTlGmmutKLoy2/viwohSeD0pRasjx7r?blocks=hide  )

AP - 238484
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54290650-b9188380-4581-11e9-85ec-b820d3da1aa5.png)

**Comment by imazlout** [comment]
Ready for Test.

Fire Final populates on Final Inspection milestone. As for Ceiling and Framing, I copied the formula for Insulation to ceiling and framing, since according to airtable, those 3 inspections seem to populate for the same scenarios. So now 5 inspections total populate (ceiling, framing, insulation, fire final, building final).

If NOT (ConstrType = "FOUNDATION" OR ConstrType = "FOUN-SLAB" OR ConstrType = "NOCHANG" OR ConstrType = "OWNERCH" OR ConstrType = "RETAINWALL" OR ConstrType = "STEPS" OR ConstrType = "WIND" OR ConstrType = "SOLAR" OR ConstrType = "POOLIN" OR ConstrType = "DECK>500" OR ConstrType = "DECK500" OR ConstrType = "POOLABOV") Then
			AddOnCondition = True
End If

**Comment by ABonomo21** [comment]
Correct inspections generated-MCoffman

Permit# 238969-Non-Residential Change of use-Corrected
![image](https://user-images.githubusercontent.com/47611580/54711093-85100600-4b1f-11e9-8ffd-72217cd36d38.png)

Permit# 238970-Non-Residential Change of use within a town-Corrected
![image](https://user-images.githubusercontent.com/47611580/54712431-a6262600-4b22-11e9-8bf5-af12537afe35.png)
