### ISSUE TITLE
PLANNING - PWCONSTRUC Pages fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#309]
Application did not populate per page fee after adding 10 no of pages. It went thru all approval process without denying to stage  progress for fees. VKAPOOR

![image](https://user-images.githubusercontent.com/4129185/54291472-f92c3600-4582-11e9-8946-521553ce0367.png)

**Comment by megisys** [comment]
In Hansen 7 what is the Fee Called please.

Thanks

DAn

**Comment by dhenry-KCI** [comment]
ENGINEERING PER SHEET FEE
![image](https://user-images.githubusercontent.com/4129185/54376928-7a0a3100-465a-11e9-8109-0056c3c3f800.png)

**Comment by goggansd** [comment]
![image](https://user-images.githubusercontent.com/28841997/54536638-6ff07700-4967-11e9-8bd9-4a4dcec0542f.png)
This issue is due to the fact that Mike and Ashley did not want the ENGINEERING PER SHEET FEE to add in the Add Fees milestone, instead opting for the Add Revision Fees Milestone. So it will ONLY add if there are revisions.

**Comment by dhenry-KCI** [comment]
Vijay is aware of this. Areed
