### ISSUE TITLE
Building- NonRes Foundation - Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#311]
The system is generating extra inspections for the a Non-Res AP with a Construction Type = Foundation. The system generated additional inspections for Backfill, Framing and Ceiling. The system should only populate inspections for Footing,  Foundation / Slab and Final Inspection.

AP - 238485
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54293186-dcddc880-4585-11e9-8f71-e7d343337e72.png)

**Comment by imazlout** [comment]
Framing and Ceiling don't generate anymore, however the system added the backfill inspection because per airtable, backfill should add if New, Core, Addition, or accessory. The work type of ap 238485 = New, which is why it added (formula just checks that Work type is not "Alter", same as H7).  @ABonomo21 Should I change it to only add Backfill if Construction type = Core, Addition, ACC399, ACC400? Please let me know the details of when Backfill should add and I'll go ahead and make the change

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/54712297-4def2400-4b22-11e9-9fb6-0fab9a3d02f7.png)

**Comment by megisys** [comment]
PLease Restest

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55559100-80208a00-56bb-11e9-8c50-5ca1d7286d52.png)
