### ISSUE TITLE
Building - NonRes (Foundation) - Required Fire Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#312]
The system is redlining the Non Res Foundation AP, requiring the user to relate a fire permit as a child building application. A related fire permit is NOT required for a Non Res - Foundation AP.

AP - 238485
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54293523-83c26480-4586-11e9-9030-c95274e84c7e.png)

**Comment by imazlout** [comment]
Per airtable Fire permit is required for New, Core, addition, and accessory. Since this application tested has a worktype = New, that's why it redlined. Similar to question for #311, @ABonomo21 Please let me know the details of when fire permit is required for nonresbldg and I'll go ahead and make the change

**Comment by ABonomo21** [comment]
See highlighted section from AirTable 

![image](https://user-images.githubusercontent.com/47611580/54711987-8d694080-4b21-11e9-913b-52a001dc28c0.png)

**Comment by megisys** [comment]
Ready for Retest......

**Comment by ABonomo21** [comment]
confirmed fixed-aw
![image](https://user-images.githubusercontent.com/47611580/55353836-40c32500-5492-11e9-92ee-47c6b63584a1.png)
