### ISSUE TITLE
Licensed Homebuilder Search Not Working

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#325]
When trying to search for a licensed HomeBuilder on all residential permits. You can not search for the license holder under the Licensed Contact category. You have to search for them under the Other Contact  category and then once you have selected the home builder, then change the category to Licensed Contact.-AW

![image](https://user-images.githubusercontent.com/47611580/54366702-7de08800-4647-11e9-8efc-3f07bc7c8714.png)

![image](https://user-images.githubusercontent.com/47611580/54366750-8fc22b00-4647-11e9-859f-b3303ac3e3ad.png)

![image](https://user-images.githubusercontent.com/47611580/54366858-bda76f80-4647-11e9-9f04-d8acdab76523.png)

**Comment by imazlout** [comment]
Could be training or maybe migration related? assigning to Dan and Dustin to discuss

**Comment by megisys** [comment]
This is correct functionality.. They are other COntacts by the way the system is written.. training Issue..

**Comment by ABonomo21** [comment]
They are not an other, they are a licensed contact, you should be able to search by the professional id no matter what contact type you are in.

**Comment by goggansd** [comment]
@ABonomo21 and @dhenry-KCI, the system is designed to look for specific criteria when looking for "Licensed Contact" records. Using the Contact and Property Browser illustrates Dan's point pretty well, as Ryan Homes is not a Licensed Contact in the IPSTest environment, as defined by the system's business rules and Frederick County's migrated data (note the highlighted items in the screenshot below.
![image](https://user-images.githubusercontent.com/28841997/55583437-da3b4280-56ef-11e9-8418-19b56456ba69.png)
Now, this could be due to a data migration issue (if, let's say, there are licenses for Ryan Homes in V7 that should have migrated), or it could be a training/expectations issue (meaning that if you want Ryan Homes to show up as a Licensed Contact, you'll need to give them a valid license--in this case, their BUSLIC contractor's license expired on 3/1/2019).

![image](https://user-images.githubusercontent.com/28841997/55583650-68172d80-56f0-11e9-8e6f-f31375719ebf.png)

I altered their BUSLIC expiration date to 5/1/2019, and they now appear with an Available License:

![image](https://user-images.githubusercontent.com/28841997/55583755-ab719c00-56f0-11e9-83fb-76ea2b9c66a5.png)

This allows you to search for them as a Licensed Contact, as below:
![image](https://user-images.githubusercontent.com/28841997/55584299-e3c5aa00-56f1-11e9-899b-c33b04d352ac.png)

**Comment by ABonomo21** [comment]
able to search for a home builder under licensed contact - corrected
