### ISSUE TITLE
Building - Permit Expiration - Set Application to Expired if it is Expired

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#354]
The permit expired 3/14/19 and the system did not generate anything showing that the permit is expired. Currently in Hansen 7 - we get a red line condition that states the permit is expired.  We should get some type of notification/alert that the permit is expired. 

This may be something we need to change across all AP types - would need to check with Ashlye B.

AP # 238868

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
The System should put holds on applications which are expired. Right ? @ABonomo21

**Comment by dhenry-KCI** [comment]
still not working tm 4/16/19

**Comment by goggansd** [comment]
This is now functional in IPSTest environment. A couple of notes:

1) You need to run the Batch Manager task called "Expire Building Permits" in order to expire them. Right now, this can be run manually, but it can also be scheduled to run automatically once we're live.
2) I had to make a judgement call about what to exclude from this when setting the status to expired. Essentially, I took the approach that certain other statuses would supercede the Expired status. Here is the list I opted for (meaning that permits which already have one of the statuses below would NOT be set to an Expired status by this process--even if past the expiration date):

        Closed
        Deleted
        Void
        Expired
        Final
        Stop Work

**Comment by ABonomo21** [comment]
not sure if this fixes the entire issue but the permit is showing as expired on the permit details and the check status-aw
![image](https://user-images.githubusercontent.com/47611580/57245993-28eb3d80-700a-11e9-9eed-35e21a8876a2.png)
![image](https://user-images.githubusercontent.com/47611580/57246121-85e6f380-700a-11e9-9c37-3f6dce288a0c.png)

**Comment by ABonomo21** [comment]
we need to test in pre-prod and follow up on the notification piece.

**Comment by ABonomo21** [comment]
Discussion needed with Dan

6/7/19 EP

**Comment by ABonomo21** [comment]
unable to confirm notifications

![image](https://user-images.githubusercontent.com/47611580/60119810-540e2580-974d-11e9-9877-0963a090e827.png)

Application 168647 is open
does not show it is expired

6/25/19 EP

**Comment by dhenry-KCI** [comment]
related to running nightly batch manager. Changing to duplicate / will monitor.
