### ISSUE TITLE
Building- Deck Permit - Review Population 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#36]
Deck Permit #237144-DUSWMF review generated on a deck permit when it should not have. The property is on public water.
![image](https://user-images.githubusercontent.com/47611580/52797371-be96b280-3043-11e9-9005-9067628dc666.png)

**Comment by imazlout** [comment]
@ABonomo21 Could you please provide the scenarios under which DUSWM should not generate? Is it correct to say that DUSWM should only generate if on public water/sewer and if work type = "ACCESS"? This seems to be how it was initially coded, but then there was an update done to drop the work type criteria. Should I put it back?

**Comment by dhenry-KCI** [comment]
DUSWM Scenarios
If Resbldg , and on public water and sewer than yes
If Non Res and on public water and sewer than yes
If Res Use, accessory with plumbing marked "yes"

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated formula RESUSES_DUSWMF_Review_AOC So that for Resuses, DUSWMF only gets added if worktype = "ACCESS" and Additional Plumbing is checked on detail page (In addition to parcel being on public water/sewer)

Please screenshot for proof of test (AP# 236155(does not add) and AP# 236156(adds) in DEV)

**Does not add when Plumbing = false**
<img width="960" alt="issue36_plumbingfalse" src="https://user-images.githubusercontent.com/47784290/53191134-09cb3b00-35d9-11e9-89aa-48f09c8583b9.png">

**Adds when Plumbing = True**
<img width="960" alt="issue36_plumbingtrue" src="https://user-images.githubusercontent.com/47784290/53191140-0f288580-35d9-11e9-8617-860839a56ab2.png">

**Comment by dhenry-KCI** [comment]
Confirmed close
