### ISSUE TITLE
License - Plumbing License - Migrated v7 License

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#4]
Plumbing License PM05129 was migrated from Hansen 7. The license is showing as active in IPS 11 but was expired in 2017.

* same issue logged by S. Walters with License number PA100008

Logged by Kelly V. on 2/4

![image](https://user-images.githubusercontent.com/4129185/52348856-4f8dde00-29f3-11e9-94e8-b996921a21f9.png)

**Comment by ABonomo21** [comment]
The inactive licenses are now showing as inactive however they are currently showing their process date of April 2019. Is this just due to the data migration? or will all licenses have the correct dates once the final data migration is done?-AW
![image](https://user-images.githubusercontent.com/47611580/56985004-5f7e0f80-6b55-11e9-83f9-26b0437afc9d.png)

**Comment by ABonomo21** [comment]
needs to be re-checked in Preprod currently not correct 

![image](https://user-images.githubusercontent.com/47611580/59037066-80b1da00-883e-11e9-9470-fa164851157c.png)

**Comment by ABonomo21** [comment]
fixed
