### ISSUE TITLE
Building- Sunroom- Requirement for electrical permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#45]
Sunroom permit #237161-All sunroom permits require an electrical permit. I did not check “additional electric” on the application to see if it would stop the progression of the permit and require an electrical permit and it did not.  IPS system should create the alert as well since all sunrooms require an electrical permit even if the box is checked yes or not.
![image](https://user-images.githubusercontent.com/47611580/52814862-2d3b3680-306b-11e9-8df3-80dcb6b39ffc.png)

**Comment by imazlout** [comment]
The box being checked for electrical or plumbing drives the logic for these status check showing up as well as if there are any fees, review, or inspections that are required as part of the action of checking the box. Since this was the way it was designed and it is not a simple change, I suggest that it be made part of the business process to check the boxes as required. Otherwise if deemed necessary, then we can analyze the level of effort for this change. I will wait for direction on how to proceed on this one.

**Comment by dhenry-KCI** [comment]
For the purposes of Go-Live, tech will need to confirm that electrical checkbox is marked for Sunroom during completeness check.
