### ISSUE TITLE
Building - ResUse - Ground Mounted Solar Panels - Building / Health Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#57]
The system did not generate the appropriate fees for a ResUse with Ground Mounted Solar Panels. system missing fees for Building and Health department. 

AP - 237185
Logged by A. White 2/14

![image](https://user-images.githubusercontent.com/4129185/52908505-1c461d00-3245-11e9-997e-8ef8bdc972df.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated configuration so that Building Fee is added based on whether total sqft is <=399 or >=400. Please see screenshot for proof of testing. Health Review fee is as designed, please see information below for more details (parcel did not have the expected details).

<img width="960" alt="issue57_fixed" src="https://user-images.githubusercontent.com/47784290/53041749-c47d0100-3452-11e9-9402-eba2b7779024.png">

Health Review is as designed. It wasn't added because the water/sewer type on parcel details were not set to well and/or septic. See screenshots below which show the parcel details before and after I updated it, as well as the test ran after the parcel update was made to ensure fee gets appropriately added

Before Update:
<img width="960" alt="issue57_parcelbeforeupdate" src="https://user-images.githubusercontent.com/47784290/53041770-cba40f00-3452-11e9-8621-d2abdaa3bfb0.png">

After Update:
<img width="960" alt="issue57_parcelafterupdate" src="https://user-images.githubusercontent.com/47784290/53041789-d3fc4a00-3452-11e9-986c-390efa885626.png">

Test of permit after updating parcel:
<img width="637" alt="issue57_healthfeeworks" src="https://user-images.githubusercontent.com/47784290/53041807-deb6df00-3452-11e9-9caf-d13a1eb88565.png">

**Comment by dhenry-KCI** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/4129185/53817935-22224a80-3f35-11e9-92c2-7d35fe3d22c8.png)
