### ISSUE TITLE
Building - Zoning Certificate- NRCS Project

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#58]
Selected a/p # 237214 as an approved NRCS project and the incorrect reviews populated

![image](https://user-images.githubusercontent.com/47611580/52966267-d7210880-3374-11e9-9ce1-efa08944134b.png)

Should have only generated Plan Review and Zoning Review all other agencies are exempt from review

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated configuration so that EH and PWDR do not populate if Approved NRCS is checked on the ZONINGCERT Detail Page. I unexpired the Zoning Rev so that this one and PLNREV populate on all Zoning Certificate permits. Please see screenshot for proof of testing (AP# 236134 in DEV).

<img width="960" alt="issue58_fixed" src="https://user-images.githubusercontent.com/47784290/53033000-0b143080-343e-11e9-825c-9967574ba373.png">

**Comment by imazlout** [comment]
Updated Zoning Rev to call it DPZ so that it's consistent with the rest of the AP Types. See updated Test screenshot
<img width="960" alt="issue58_fixed2" src="https://user-images.githubusercontent.com/47784290/53037554-87ac0c80-3448-11e9-841b-22f4c6b9bb7d.png">

**Comment by dhenry-KCI** [comment]
Confirmed fixed - AP238401
