### ISSUE TITLE
Home Occupation-Impact-life safety fee not generating

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#591]
The life safety fee did not generate on this Impact Home Occupation when it should have.-AW

![image](https://user-images.githubusercontent.com/47611580/55184398-67b6e980-5168-11e9-9fd3-625cc02de406.png)

![image](https://user-images.githubusercontent.com/47611580/55184411-71d8e800-5168-11e9-8806-f651c6ac1cb5.png)

**Comment by kellyjj** [comment]
I will investigate this issue.

**Comment by kellyjj** [comment]
this was tested and fixed in http://wh-ipsdevtst/ipstest/
this was caused by the detail page work for r4c.
the formula USE_ImpactFees_AOC  needed to be updated to look at either detail page.  

here is the updated formula

'kjj 4-1-19  added to the if then statement to look for other detail page


Dim res as result
For Each detailpage as Hansen.CDR.Use.IApplicationDetail in oUseApp.ApplicationDetails

If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails" then
	
	Dim oHomeDetail as InforClient.AgencyCDR.Use.HomeDetail
	oHomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent (detailpage, res)
	
	if oHomeDetail.ImpactType.Code = "IMPACT" Then

		AddOnCondition = True
	
Else
	
   AddOnCondition = False
End If

End If
Next

**Comment by ABonomo21** [comment]
confirmed fixed-aw
![image](https://user-images.githubusercontent.com/47611580/55350550-5f252280-548a-11e9-8f7c-a0456ad61f83.png)
