### ISSUE TITLE
PLANNING - PLAT - FINAL and COMBO School Construction Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#618]
"School Construction Fees Added" status check should be required before leaving Under Review. The fees should populate at the same time as the Mylar Fee, appears to be Awaiting Paperwork.
Applicant can not submit mylars without paying School Construction fees when applicable.
FINAL PLAT PL239098 COMBO PL239101
areed

![image](https://user-images.githubusercontent.com/4129185/55504007-e2c34880-561d-11e9-8c9d-9b9ccef36eda.png)

**Comment by goggansd** [comment]
This was previously configured this way. Not clear why it was changed, but I expect that fixing it back will break something else as a result. School construction fees were already configured to add in Awaiting Paperwork (same as Mylar fee), but were not adding because this status check was moved to Paperwork Review (which occurs in the workflow AFTER the Awaiting Paperwork milestone). Please retest, and look for other related issues due to addressing this one.

**Comment by dhenry-KCI** [comment]
at retest the school construction fee added status check doesnt come up.  I went to closed/finalized without entering the school construction fees box on details page.  See  Combo PL239115 and Final PL239118

**Comment by goggansd** [comment]
According to the way it was written, the Occupancy Type must be RES, with work type COMBO or FINAL. Is this correct? AP # PL239115 has Occupancy Type of NRSRGP, while AP # PL239118 has an Occupancy Type of NRSRES.

**Comment by dhenry-KCI** [comment]
looks good on Final and combo

MW
