### ISSUE TITLE
ResBldg-MPDU Fees did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#624]
The MPDU fees did not generate for this permit. The code in is the parcel so it should have recognized it and generated-AW

![image](https://user-images.githubusercontent.com/47611580/55561193-be1fad00-56bf-11e9-9303-46a392f6232d.png)
![image](https://user-images.githubusercontent.com/47611580/55561239-ced02300-56bf-11e9-8198-284ba3a4bb4e.png)

**Comment by goggansd** [comment]
This permit was created using an Address record as the primary site, rather than a parcel. The workflow formula currently checks the primary site to find the Subdivision code. In this case, it found that the primary site was an address and compared the Subdivision code to be blank:

![image](https://user-images.githubusercontent.com/28841997/55648475-6a3fc180-57ae-11e9-8bba-6a5b3901ed48.png)

If you recreate this same application using the parcel as the primary site OR change the Address record to have the correct Subdivision code, it will work:

![image](https://user-images.githubusercontent.com/28841997/55648675-ef2adb00-57ae-11e9-8253-e85914dfda13.png)

**Comment by ABonomo21** [comment]
I will have staff retest with the parcel data updated. The subdivision code should be filled in on both sections for the parcel data. 
If this works we need to make sure GIS is updating this information correctly

**Comment by ABonomo21** [comment]
We use the address to create our permits, not the parcel. Don's permit does not have an address attached to it, therefore we would not accept this as a valid permit. Need to get together with Dan and Ashlye to confirm how this process should work.-AW

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/56232646-46eb0100-604f-11e9-8da3-50b400251320.png)
