### ISSUE TITLE
Building - ResBldg - Permit Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#64]
Constructions fees do not generate. Only the Elementary and Middle school construction fees generate correctly. This issue persists throughout other condo unit permits. 

AP - 237224
Logged by A.White 2/19

![image](https://user-images.githubusercontent.com/4129185/53101378-9dc4d600-34f7-11e9-8303-6bceb1c534d6.png)

**Comment by imazlout** [comment]
Working as designed. Per the current rules:

- School Construction Fee - ES gets added for Subdivision Codes:  "S1143", "SP1211", "S1163", "S829T"
- School Construction Fee - MS gets added for Subdivision Codes: "S829T"
- School Construction Fee - HS gets added for Subdivision Codes: "S1143", "SP1211", "S829T"

In the test the user performed for AP# 237224, the address used is associated with Subdivision Code "S1163", which is why only the elementary school construction fees were added.

<img width="960" alt="issue64_workingasdesigned" src="https://user-images.githubusercontent.com/47784290/53133669-ee612100-3541-11e9-8144-3229fd63563d.png">

**Comment by ABonomo21** [comment]
S1163 Should have MS and ES school construction fees generating. This needs to be corrected, not a training issue.

**Comment by mmbanong** [comment]
Added Sub Division S1163 to fomula

**Comment by ABonomo21** [comment]
This issue is half fixed-The construction fees are generating correctly for the condo units (#238860 & #238862) but the school construction fees are also generating on the parent structure permit (#238858) which they should not generate on the parent structure. I believe this is due to the details page being not being on the permit application for Res Condos. The details tab had a checkbox to check if this permit was the parent structure. See Issue # 

Parent Structure #238858
![image](https://user-images.githubusercontent.com/47611580/54436584-29054600-4709-11e9-8b0d-20f4f5ffe250.png)

**Comment by megisys** [comment]
@imazlout

**Comment by megisys** [comment]
Please Retest.. Fixed Detail Page issue

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54689899-b6c0a700-4af6-11e9-81f7-d9e765602576.png)

![image](https://user-images.githubusercontent.com/47611580/54689952-cb04a400-4af6-11e9-826c-4c36f84d9f6e.png)
