### ISSUE TITLE
Planning-REZONE-hearing milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#645]
Two hearings are needed.  I resulted the PC hearing but not the Council hearing but still progressed to awaiting paperwork.  Needs to stay in hearing milestone until all hearings are resulted.-MW

![image](https://user-images.githubusercontent.com/4129185/55628073-c0e0d780-577d-11e9-9025-40fb7ec3f451.png)

**Comment by goggansd** [comment]
This issue would have actually impacted multiple AP Types, as a number of them are now using the same formula. The issue was introduced by adding this formula used elsewhere to address the issue in which results of Deferred were not being handled correctly. Corrected in IPSTest (see RZ239134). Should work similarly for other AP Types which had the Deferred hearing result issue corrected previously.

**Comment by dhenry-KCI** [comment]
the only issue now is that I denied a hearing, added another of they same type and approved it, but I am still stuck in hearing-MW

![image](https://user-images.githubusercontent.com/4129185/55629722-e8d23a00-5781-11e9-829c-012df7a23383.png)

**Comment by goggansd** [comment]
I actually just fixed this for another issue. Please retest...

**Comment by dhenry-KCI** [comment]
still holding up after resulting hearing

![image](https://user-images.githubusercontent.com/4129185/55632171-c04d3e80-5787-11e9-827b-a6407ff68287.png)

**Comment by dhenry-KCI** [comment]
denied council meeting and it stage progressed to awaiting papwerwork

MW

![image](https://user-images.githubusercontent.com/4129185/55743821-4b853900-5a01-11e9-9f1d-578f3956b81b.png)

**Comment by dhenry-KCI** [comment]
still broken  MW

**Comment by dhenry-KCI** [comment]
fixed per RZ239196
