### ISSUE TITLE
Fire - Fire Permit - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#67]
The fire permit application was issued without the parent building permit being attached. For Fire Permit #237208 - The permit is supposed to be the fire suppression permit for the above single family dwelling #237202. There is not a checkbox on the fire permit applications to mark that there is a parent building permit required. 

This also happened with fire permit #237219 and persists through all other fire permits tested. 

AP - 237208, 237202 & 237219
Logged by A.White 2/18

![image](https://user-images.githubusercontent.com/4129185/53105258-c3091280-34fe-11e9-8816-3e92d9eca750.png)

**Comment by imazlout** [comment]
This is not an issue since RESBLDG Permit requires a child fire application once it reaches inspections milestone. It is working as designed. Since RESBLDG requires a fire permit be attached, it's redundant for the same requirement to be on Fire permit as well. Will wait for direction from project management (@dhenry-KCI ) on whether I should duplicate the functionality or not.

**Comment by ABonomo21** [comment]
Agreed this is a training issue, the technician should have checked during the completeness check if a building permit was required that is was attached and is already issued. 

If it was not attached and one was required that did not exist in the system, the application should have been marked resubmit at completeness check. Same if the building permit application is pending issuance.
