### ISSUE TITLE
Building - Capacity - Preliminary Fixture Count

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#712]
The system should sum the Fixture Value field within the preliminary fixture count field and display that value in the Addl FU field above the Preliminary Fixture County grid.

![Add FU](https://user-images.githubusercontent.com/4129185/56293152-91738880-60f6-11e9-8775-baf563c99d61.PNG)

**Comment by megisys** [comment]
If this is during Intake this will not happen.. It happens after a save.

**Comment by goggansd** [comment]
Not sure why this has been kicked back as a bug, but I think that megisys's comment above means that there isn't a way to have the field update in real time. The intake person has to save the detail page and open it again in order to see the calculated value. Is it not doing this, or was this issue kicked back because megisys's reply is not an accepted response?

**Comment by megisys** [comment]
Also the Qty are not set to 1.

**Comment by ABonomo21** [comment]
Showed Dan did not update

**Comment by megisys** [comment]
Qty Now Required

**Comment by JuanitaMiles** [comment]
Appears to summing as expected for now.
