### ISSUE TITLE
Building - Capacity - Adjustment Factor

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#723]
The Capacity Adjustment Factor should auto - populate based on the user selected Business Classification with the exception of the following which would be user defined:
- CAR - Carwash
- IRR - Irrigation
- MAN - Manufacturing
- POL - Pool

Issue logged already that will allow user to edit capacity adjustment factor. future enhancement to include above functionality.

**Comment by dhenry-KCI** [comment]
Add Laundromat to the list above. DUSWM needs the ability to edit the values for these fields.

**Comment by goggansd** [comment]
After deeper digging on this one and the previous related one, it looks like megisys added a code table field called CALCULATIONS, in which are now populated a calculation value, where applicable. I have altered the workflow formulas to use the code table CALCULATIONS field value instead of the hardcoded list provided in the other ticket. This means that Frederick County will be able to maintain the calculations in a code table, so if any one is incorrect or needs adjustment to work correctly going forward, a system admin need only change the CALCULATIONS bvalue associated with the Business Class in the code table. I also made the Caf field enabled for editing.

The workflow will now automatically populate a value from the code table's CALCULATIONS field based on the selected Business Class--but ONLY if the existing Caf value is empty or zero. This means if you need to have it recalculate for some reason, you'll need to clear out the Caf field value first, then select your Business Class. But if you have to manually input a Caf (as in the cases requested above), you can EITHER select the Business Class first and THEN set the Caf manually OR you can set the Caf manually AND THEN select your Business Class.

This has been addressed in the IPSTest environment.

**Comment by ABonomo21** [comment]
Quantity x fixture unit cost x capacity adj. factor

![image](https://user-images.githubusercontent.com/47611580/57232937-aeabc080-6feb-11e9-892c-934c0d4291cc.png)

Need to add a column on the fees for CAF

![image](https://user-images.githubusercontent.com/47611580/57232874-9176f200-6feb-11e9-936a-14d51ff0584e.png)

**Comment by JuanitaMiles** [comment]
Will keep the CAF field on the details page only for now. might be nice to have in the future.

**Comment by JuanitaMiles** [comment]
Still cannot manually update the Capacity Adjustment Factor for the five Business Classifications identified above. Can input a value but the value changes back to 0.00 upon saving.

**Comment by megisys** [comment]
Add new Field

**Comment by JuanitaMiles** [comment]
I was able to manually input an Override CAF value and it saved on the detail page. The fees that result will need to be tested as a whole.

![image](https://user-images.githubusercontent.com/31770504/65447769-45dfac00-de05-11e9-857d-1886047ab52b.png)
