### ISSUE TITLE
Planning-Yardmod-letter issued condition

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#732]
project shouldnt go to finalized with an open condition.  It should go to "issue letter" just like Verification APs do.

![image](https://user-images.githubusercontent.com/4129185/56307735-909d1f80-6113-11e9-88b8-e4c1bd39e29e.png)

MW

**Comment by goggansd** [comment]
As far as I can tell, the configuration of these two AP Types is exactly the same with regard to the Issue Letter milestone and the Letter condition and related status checks. Looking at the cited application number, it seems that the Letter condition added on 4/17/2019 at 13:15 (see your screenshot above), which is the same time the application hit the Issue Letter milestone (see my screenshot below). This is consistent with what is configured for both AP Types. The application did not move from Issue Letter to Complete until 4/17/2019 at 13:26 (nine minutes later), indicating that the application was stopped (again, as designed for both AP Types) for nine minutes until the Letter condition was approved, before going to the Complete milestone. Both AP Types cited have configuration which should have this same behavior.

What is the actual issue here? Is the Letter condition supposed to add in a different milestone? Or is it not supposed to go to the Complete milestone once approved? Or what?

**Comment by dhenry-KCI** [comment]
did it again.  Dan saw it happen :0

**Comment by dhenry-KCI** [comment]
ok per YD239431

MW
