### ISSUE TITLE
Building - ZoningCert - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#80]
The zoning certificate closed and finalized with the two trade permits still open.

AP - 237190
Logged by 2/15

![image](https://user-images.githubusercontent.com/4129185/53109689-64946200-3507-11e9-8fc9-a37ff2003f71.png)

**Comment by imazlout** [comment]
This is the same as Issue #68 Training is needed on this functionality as this is working as designed. Inspections are to be scheduled first, before they are resulted. Once the user goes to schedule the final inspection, if the trade permits are not finaled, the user will receive an error like the one in the screenshot below, where I tested this function successfully (ZONINGCERT: AP# 236135 ELECPERM: AP# 236150 in DEV). In practice I believe this won't really come up since Inspectors always schedule their inspections before they go onsite to inspect, however the users should still be trained to enter the schedule date for an inspection before resulting it as part of proper business process.

<img width="960" alt="issue80_workingasdesigned" src="https://user-images.githubusercontent.com/47784290/53136743-0c348300-354e-11e9-9d40-504f23ad52eb.png">

**Comment by ABonomo21** [comment]
Agreed- We need to make sure staff is trained to know that inspections should be scheduled prior to being resulted. 
This will affect inspectors using mobile and administrative staff using the back office (in the event and inspection is requested at the customer service counter, email or phone) when this project goes live- in the future all inspection request should be submitted via the portal.
