### ISSUE TITLE
Building Permits - Fee Payment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#852]
When fees are paid on a permit application the person who processed the fee payment shows up in the processed box. It should generate the techs id who results the completeness check review. 
![image](https://user-images.githubusercontent.com/47611580/57467351-60e3c200-7250-11e9-8fdb-3ccd5453ac23.png)

**Comment by goggansd** [comment]
This is an automatic feature of the IPS application whenever the application workflow set the Processed date. In this case, the Processed Date is set when the workflow enters the Under Review milestone, which was caused by Emily paying the fees (and so it says Emily was the one who processed it, since the system entered the Under Review milestone due to her actions):

![image](https://user-images.githubusercontent.com/28841997/57527872-bbd3f280-72fe-11e9-88da-4f1fc153ea1d.png)

The only way to address this would be to change the milestone under which the Processed Date is set. In order for it to behave as you describe, I would recommend that we move it so it sets at either Application Added or Completeness Check, depending on the back office workflow and which person you really want to appear as the Processed By person (i.e. the Intake person or the Completeness Check person).

**Comment by megisys** [comment]
Ashlye it is about which user got it to the processed status milestone of Under Review. This is standard functionality. We dont really use this for much..

**Comment by ABonomo21** [comment]
Dan as discussed the tech who approved the completeness check should be the name under processed 

related to notification issue on  #853

**Comment by megisys** [comment]
Created Formula BP_SetprocessedbyComplete_BU4
Updated all building Permit Workflow to remove system settting date
