### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#853]
When fee was paid on a permit processed by Abbie- the email notification was sent to Emily who paid the fee- 
![image](https://user-images.githubusercontent.com/47611580/57467459-9dafb900-7250-11e9-9c4c-5184dece94dc.png)

**Comment by goggansd** [comment]
This is not a bug--it is how test mode is designed to work. Whichever IPS user is logged in and causes the application to advance to the milestone in which the notification is sent gets the email instead of the applicant--or, in this case, instead of the person who created and/or processed the permit.

**Comment by ABonomo21** [comment]
per dan this way on purpose for testing.
