### ISSUE TITLE
r4c - fro details page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#871]
the details page for FRO populated, however, I do not like the way that it is laid out and feel that it should be more laid out like the details page in IPS.

tiffany martin 5/10/19

**Comment by calequin** [comment]
added spacing for it to determine a different field. My suggestion is to add a label that can help the applicant identify what the boxes are for.  R4C does not render the boxes like in ips backoffice because it is built for the rendering to be used in a mobile and laptop/desktop device. Therefore the rendering is subjective to the numbering we set up in the back office.
![image](https://user-images.githubusercontent.com/47603568/57637054-132cc980-7570-11e9-9786-ea07e850eba6.png)

**Comment by calequin** [comment]
adding labels
![image](https://user-images.githubusercontent.com/47603568/57741156-68103300-7689-11e9-8d83-579b8da6560c.png)

**Comment by dhenry-KCI** [comment]
OK TM 5/22/19
