### ISSUE TITLE
r4c - fro - project # on details page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#872]
a project number was input in R4C but did not carry over to IPS and the valuation did not pull from the project # so we know what the applicant should post as far as a guarantee.

**Comment by goggansd** [comment]
Without an AP number, I can't be certain, but since only two FROPERMITS have been added recently (240653 and 240654), and since both have the same Planning FRO related to them, isn't the Planning FRO AP number 14476? (Example screenshot from 240654 Related Records tab):

![image](https://user-images.githubusercontent.com/28841997/57536378-132f8e00-7312-11e9-849b-aacc914260c7.png)

**Comment by dhenry-KCI** [comment]
CLOSING TM 5/14/19

**Comment by dhenry-KCI** [comment]
We have agreed to do a manual check 5/14/19
