### ISSUE TITLE
building - fro - under review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#873]
the FRO permit went straight to under review and did not generate fees for permit #240654. Also, the NOT_PRFEES notification populated and we are not sure what this is for.

tiffany martin 5/10/19

**Comment by goggansd** [comment]
This is because there is only one fee which adds automatically on FROPERMIT applications,and it is set to add only if BOTH Town and County Board are not checked on the detail page. In this case, the County Board box was checked:

![image](https://user-images.githubusercontent.com/28841997/57535788-e464e800-7310-11e9-839f-1f6e3a98f03f.png)

This resulted in the application not adding any fees. Since the only status check on the Awaiting Plan Review Payment milestone is one to ensure that all fees have been paid in full, the application proceeded to the next milestone:

![image](https://user-images.githubusercontent.com/28841997/57535912-1fffb200-7311-11e9-94be-82e7d6325f3b.png)

If this is not correct, what should happen in this scenario?

**Comment by ABonomo21** [comment]
retested - see permit #240729 the box for FRO was checked and this notification still populated.

![image](https://user-images.githubusercontent.com/47611580/57854464-482a5d80-77b6-11e9-8a99-a62c3737e569.png)
 

tm/ ep

**Comment by megisys** [comment]
Ready for ReTest in New Environment

**Comment by ABonomo21** [comment]
Retested. Corrected.

Thank you.
6/6/19 EP
