### ISSUE TITLE
building - fro - fro easement

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#877]
i am not sure if the system looks, but it should look to see if the easement has been recorded prior to approval of the FRO permit. If the easement is not recorded then the permit cannot be issued until such time.

logged by tiffany martin 5/10/19

**Comment by megisys** [comment]
This is what needs to be checked during intake review. This is a SOP of Intake

**Comment by ABonomo21** [comment]
I thought the system was going to be able to do this for us and not issue until recordation information was completed under the planning application?? We did discuss this way back in the beginning. Otherwise, the easement will never be recorded when the FRO permit application is created since that happens later in the process which means every FRO application will immediately be put on held until 7-10 days from the time legal documents are submitted. The Planning number is linked to ALL FRO permit applications. If there is no system hold up, all permits will roll straight to issued without having that checked...

**Comment by dhenry-KCI** [comment]
Per discussion with County, some FRO permits can be created before the easement is recorded. Will need this process is reviewed during intake review.
