### ISSUE TITLE
Building - ZoneCert - Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#90]
When trying to add the Re-Inspection fee it was not available to add 

AP - 237139
Logged by K.Vanaman 2/11

![image](https://user-images.githubusercontent.com/4129185/53113304-4468a100-350f-11e9-8a6f-d26396a488e5.png)

**Comment by imazlout** [comment]
Sent email to @ABonomo21 and awaiting response on how to proceed. Related to Issue #89

**Comment by imazlout** [comment]
@ABonomo21 Kelly V. put in a couple of issues about ZoningCert missing a re-inspection fee. I checked the previous system and saw that this particular AP Type never had a re-inspection fee in its config. Do you want me to add it so that this ap type does have the ability to have re-inspection fees added moving forward? If so, is it $48 like it is for the others? 
(This is related to #89)

**Comment by ABonomo21** [comment]
Yes. This a/p type would require a re-inspection fee just like the others and should follow the same rules. After two inspection every subsequent inspection requires a $48.00 re-inspection fee.

**Comment by imazlout** [comment]
Ready for Test
Added re-inspection fee for ZONINGCERT.
<img width="960" alt="issue90_added" src="https://user-images.githubusercontent.com/47784290/53653929-7ddd9280-3c1a-11e9-88e1-5644e2171351.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fixed-aw
![image](https://user-images.githubusercontent.com/4129185/53820409-b7274280-3f39-11e9-973c-38cce79f06f1.png)
