### ISSUE TITLE
Building - RESTWN - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#91]
When creating a RESBLDG AP for a new RESTWN the system generated incorrect fees. Correct fees should be:
Building Fee = $572
DT State Home BUilder Fee = $50

SCD and Minor Grading permit should not have generated.

AP237203
Logged by M. Coffman 2/18

![newtown1](https://user-images.githubusercontent.com/4129185/53139731-9550b780-3558-11e9-91a8-7a17a1e05f59.png)
![newtown2](https://user-images.githubusercontent.com/4129185/53139732-95e94e00-3558-11e9-9182-4aec4b7d23fc.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated fee value for Building Fee so that it displays the correct value. Updated formula for SCD and Minor Permit Fee so that they don't show in this scenario. Homebuilder fee did not add because the applicant did not have a valid homebuilder license. The applicant must have a license for the fee to add in this scenario (see screenshot below).

Please screenshot for proof of test (AP# 236152 in DEV)
<img width="960" alt="issue91_fixed" src="https://user-images.githubusercontent.com/47784290/53186245-a0dec580-35ce-11e9-9419-80f697dfacfc.png">

No License:
<img width="960" alt="issue91_nolicense" src="https://user-images.githubusercontent.com/47784290/53186262-a6d4a680-35ce-11e9-90ab-b94829affaaf.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fixed
![2](https://user-images.githubusercontent.com/4129185/53252328-9edb3c00-368c-11e9-94e3-6ffb0d68a666.jpg)
