### ISSUE TITLE
IPS Pre Prod-Electric & Plumbing License-Renewal fee automatically generating

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#947]
After the license issued, it went into the correct milestone of "Awaiting Renewal Details" but the renewal fee of $158 automatically generated. The renewal fee should not be added to the license until we receive the renewal application from the applicant and after we confirm the license details. this is happening for both plumbing and electric licenses.-AW see #963
![image](https://user-images.githubusercontent.com/47611580/58180901-d56b2780-7c78-11e9-9767-7a851015b16f.png)

**Comment by calequin** [comment]
The fees and renewal details are both stopped in the same milestone. This is in order to force the applicant to pay the fees and add the details prior to issuance. Once fees are paid and details uploaded the milestone progresses to Renewal Review. This is the same design we've had in both test and conference room pilots.

**Comment by ABonomo21** [comment]
See issue #1262 We are unable to test the renewals for trade licenses until the in life mapping is complete for trade licenses-AW

**Comment by dhenry-KCI** [comment]
will move to ready for re-test once data migration and in-life mapping is complete.

**Comment by ABonomo21** [comment]
closing this was in preprod- will add back if needed
