### ISSUE TITLE
IPS Pre Prod- Duplicated Contact Records

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#959]
PM01331 _ multiple contact of the same name converted over under the relationships section

![image](https://user-images.githubusercontent.com/47611580/58186403-cdb08080-7c82-11e9-9e9c-2a161f7d4a50.png)

only in once in H7 on the actual license- in as company/contacts 3 times 
I thought duplicated contacts were being cleaned up prior to migration?? 

![image](https://user-images.githubusercontent.com/47611580/58186486-f769a780-7c82-11e9-9b8e-8da8e68f7ad4.png)

![image](https://user-images.githubusercontent.com/47611580/58186532-136d4900-7c83-11e9-9d50-b16f3bda3fd0.png)

**Comment by JuanitaMiles** [comment]
The Data for this issue is consistent between both TEST and PREPROD.

The Mark S Martin contact record has (3) Relationships:
   1. PIPE DOCTOR PLUMBING & HEATING (1)
      - This relationship occurred through the creation of License # PM01017. The PIPE 
        DOCTOR PLUMBING & HEATING contact record only has a single Relationship.
   2. PIPE DOCTOR/MARK S MARTIN (2)
       - This relationship occurred through the creation of License # PM01331. The PIPE 
         DOCTOR/MARK S MARTIN contact record has duplicate Relationship records. (see 
         issue #960 ) It is likely that the duplicate Relationships showing in the Contact and 
         Property Browser in the below screenshot stem from the duplicate Relationships on the Contact 
         record cited in issue 960)

![image](https://user-images.githubusercontent.com/31770504/58481911-5cae1480-812b-11e9-9aa7-db0c60b7aead.png)

**In addition, if I search for Pipe Doc% in either environment, I get only two (unique) contact records. One for PIPE DOCTOR PLUMBING & HEATING, and one for PIPE DOCTOR/MARK S MARTIN. This appears to be inconsistent with the Contact Browser screenshot from Hv7 above.**

![image](https://user-images.githubusercontent.com/31770504/58482397-4d7b9680-812c-11e9-8339-9bdd62b45a99.png)

![image](https://user-images.githubusercontent.com/31770504/58482448-5c624900-812c-11e9-95ae-ce1e9fcb655c.png)

**Comment by ABonomo21** [comment]
not an issue- confirmed with Dan and Juanita
