### ISSUE TITLE
Building - Demo - Electrical Detail Codes

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#96]
Missing selection of "demo" from residential electrical permit details. Fee is $48.00

Logged. M. Cofffman
![res ele_fee](https://user-images.githubusercontent.com/4129185/53141579-9e448780-355e-11e9-9109-5e7765d1eacc.png)

**Comment by imazlout** [comment]
I updated the config so that the ELECTRICAL RES DEMOLITION  and ELECTRICAL NONRES DEMOLITION get added when worktype = "REMOVE" and occupancy code starts with Nonres%/Res%, respectively (Per current PROD H7 config). That part only is ready for test once changes are moved to Test Environment.

Regarding adding a code of "Demo" to The Residential Electrical Details grid, I wasn't able to access Hansen7 to see what the exact value is so that I can copy it (It should be the same to avoid errors with conversion). This is no worries because as long as the code doesn't drive any formulas, it's very easy to add a new code value to the Code Definition Management. In this scenario, the admin would add a new code to Enhancement Code Tables ->AgencyCDR -> Building -> **ElectricDetail**

See screenshots below for proof of test:

RES:
<img width="960" alt="issue96_res" src="https://user-images.githubusercontent.com/47784290/53207374-896d0000-3601-11e9-9dbb-e165fd5efc47.png">

NONRES:
<img width="960" alt="issue96_nonres" src="https://user-images.githubusercontent.com/47784290/53207357-807c2e80-3601-11e9-8fbb-0f900cd77cb6.png">

**Comment by dhenry-KCI** [comment]
@imazlout - the code is not in Hansen7 for a residential permit. So we don't need to match Demo code to an existing Hansen 7 code. Can you create a demo Res code for use with this AP

**Comment by imazlout** [comment]
Ready to Test.

Added new code for Residential Electrical Details called "DEMO - Demolition"

<img width="960" alt="issue96_added" src="https://user-images.githubusercontent.com/47784290/53655939-a87e1a00-3c1f-11e9-9c5e-07953e4a5ae4.png">

**Comment by dhenry-KCI** [comment]
![96 fixed](https://user-images.githubusercontent.com/4129185/53742977-d190eb80-3e67-11e9-8df8-576b297a2bf3.PNG)
![96 fix 2](https://user-images.githubusercontent.com/4129185/53742978-d2298200-3e67-11e9-878b-3af6714fc0b4.PNG)

Fixed - 3/4/19 - KVanaman
