### ISSUE TITLE
IPS Pre Prod- Missing Fields- Contact Records

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#966]
![image](https://user-images.githubusercontent.com/47611580/58187580-04879600-7c85-11e9-9d88-a49c2b6044c0.png)

IPS is missing Reference number 
![image](https://user-images.githubusercontent.com/47611580/58187634-25e88200-7c85-11e9-9dfa-49fabde7a76b.png)

and Missing Position Field
![image](https://user-images.githubusercontent.com/47611580/58187659-3567cb00-7c85-11e9-9582-38ecee1ce736.png)

**Comment by megisys** [comment]
Reference is on the Contact Record. See the first screen shot.

**Comment by JuanitaMiles** [comment]
The Data issues identified occur in both TEST and PreProd.

_(Joseph L Ciaccio does not exist in TEST, so I did a test on Kenneth J Babineau, and the same issues outlined above persist.)_

The Position field from Hv7 does not appear anywhere in IPS on the Customer or Contractor contact records (TEST or PREPROD).

The Reference # appears to translate to the Professional ID field on the Business/Contractor contact record only. It currently does not populate in the Professional ID field on the Individual/Customer contact record. All of the licenses for the Individual/Customer show on the Licenses tab of the Contact InfoViewer only.

 
![image](https://user-images.githubusercontent.com/31770504/58489842-0dbbab80-813a-11e9-9d9e-da45d5c2805c.png)

![image](https://user-images.githubusercontent.com/31770504/58489902-2f1c9780-813a-11e9-8f96-5960d6cb2584.png)


@ABonomo21 @dhenry-KCI **Need to confirm if the Professional ID as it exists now is sufficient for the County, and what to do about the Position field. Changing Labels to 'Question' since more discussion may be needed, and 'Data Issue' as the issues persist in both TEST and PREPROD.**

**Comment by ABonomo21** [comment]
all issues resolved - position moved

![image](https://user-images.githubusercontent.com/47611580/58975797-d4b3b480-8793-11e9-8e0a-9984b8b25aeb.png)

Dan explained the Licenses for contact vs. available license
